---
- name: "Installation Wordpress"
  hosts: prod
  become: true
  vars_files:
    - ../files/secrets/credentials.yml
  vars:
    system_user: "{{ ansible_user }}"
  pre_tasks:
    - name: "delete nginx"
      yum:
        name: nginx
        state: removed
    - name: "creation user www-data"
      user:
        name: www-data
        state: present
    - name: download docker_compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
  roles:
    - ansible-role-containerized-wordpress      

